version: '3.9'

services:
  app:  
    build: 
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    environment:
      - DEBUG=1
      - SECTRET_KEY=hehehe
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=devpass
    depends_on:
      - db
  
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpass
